### PR TITLE
Updated electGap regex

### PR DESCRIPTION
**Pull request by oddaaron00**
Now includes all punctuation found in `tokenisers.py`

### CODE REVIEW

**Comment by oddaaron00** [comment]
Jesus Christ I am so out of my depth when it comes to interactive debasing lmao, sorry about the list of commits always being so long

**Comment by oddaaron00** [comment]
How am I making this worse oh my god

**Comment by oddaaron00** [comment]
Okay I FINALLY figured it out, I think this is sorted now haha

**Review by d33tah — APPROVED** [review]

**Comment by d33tah** [comment]
LGTM, though I hadn't tested the code. Let's wait for @ftyers to also review this.

**Comment by ftyers** [comment]
LGTM :)

**Pull request merged**
