### PR TITLE
Issue #46 fix

### LINKED ISSUE #46: Choosing wrong multiple choice doesn't generate red cross

### PR DESCRIPTION
**Pull request by oddaaron00**
Resolves #46

### CODE REVIEW

**Comment by oddaaron00** [comment]
Sorry about all the extra commits here, it's still a fix for #46 haha

**Comment by ftyers** [comment]
Is it ok if I squash this before merging?

**Comment by oddaaron00** [comment]
> Is it ok if I squash this before merging? @oddaaron00

Of course. I did search around about squashing commits but it's not something I've done before so I didn't trust myself.

**Comment by ftyers** [comment]
Thanks! :)

**Pull request merged**
