### PR TITLE
Changes the gap selection algorithm so it uses regex to exclude punctuation

### LINKED ISSUE #9: Don't turn punctuation into gaps

### PR DESCRIPTION
**Pull request by oddaaron00**
Fixes #9

### CODE REVIEW

**Comment by ftyers** [comment]
Maybe remove ' from that ? Also, the way the tokenisation works sometimes we get multiple punctuation items in the same token, e.g. `("`, does it take care of that?

**Comment by oddaaron00** [comment]
> Maybe remove ' from that ? Also, the way the tokenisation works sometimes we get multiple punctuation items in the same token, e.g. `("`, does it take care of that?

I've removed the ' and added ( and ) to the regex. It'll match any token that contains any of the characters in the square brackets so yes, it does.

**Comment by ftyers** [comment]
Ok, this looks good as is, but might be worth adding the other punctuation symbols found in `tokenisers.py` too:
```
!#%&'()*+,-./:;<=>?@\`|~¡«°·»¿،؛؟٪٫٬।৷৹–—―‘’“”„‟…‹›↓̣$€½
```

**Comment by oddaaron00** [comment]
I'm not at my PC right now but I'll add those tomorrow if that's alright

**Comment by ftyers** [comment]
@oddaaron00 sure! Thanks :)

**Comment by ftyers** [comment]
I've merged this, but please send another PR with the rest of the punctuation :)

**Pull request merged**
